# Generated by Django 5.2.6 on 2025-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('desktop', 'Desktop Application'), ('api', 'API/Backend'), ('other', 'Other')], default='web', max_length=20),
        ),
    ]
